variables:
  bots:
    - id: SimpleHost
      name: Simple Host Bot


parameters:
  - ${{ each bot in variables.bots }}:
    - name: '${{ bot.id }}'
      displayName: '${{ bot.name }}'
      type: string
      default: 'x86,x64'
