

jobs:
  - job:
    steps:
      - powershell: |
          Write-Error "error:"
        ${{ if eq(variables['var-a'], '') }}:
          displayName: 1
        ${{ if ne(variables['var-a'], '') }}:
          displayName: 2
