stages:
- stage: bffnsimplehostbotdotnet
  jobs: 
    - job:
      steps: 
        - powershell: echo "test"

- stage: bffnsimplehostbotdotnet21
  jobs: 
    - job:
      steps: 
        - powershell: echo "test"

- stage: bffnechoskillbotdotnet
  jobs: 
    - job:
      steps: 
        - powershell: echo "test"

- stage: bffnechoskillbotdotnet21
  jobs: 
    - job:
      steps: 
        - powershell: echo "test"

- stage: bffnechoskillbotdotnetv3
  jobs: 
    - job:
      steps: 
        - powershell: echo "test"

- stage: bffnwaterfallhostbotdotnet
  jobs: 
    - job:
      steps: 
        - powershell: echo "test"

- stage: Deploy
  dependsOn: 
    bffnsimplehostbotdotnet
    bffnsimplehostbotdotnet21
    bffnechoskillbotdotnet
    bffnechoskillbotdotnet21
    bffnechoskillbotdotnetv3
  jobs:
    - job: Test
      strategy:
        maxParallel: 3
        matrix:
          bffnsimplehostbotdotnet: {}
          bffnsimplehostbotdotnet21: {}
          bffnechoskillbotdotnet: {}
          bffnechoskillbotdotnet21: {}
          bffnechoskillbotdotnetv3: {}
      steps: 
        - powershell: echo "test"