stages:
- stage: A
  jobs:
    - job: 
      steps:
        - powershell: |
            Write-Host "##vso[task.setvariable variable=StepVariable;isOutput=true]1"
          displayName: A

- stage: B
  condition: eq(variables.counter, 1)
  jobs:
    - job: 
      steps:
        - powershell: |
            Write-Host "test"
          displayName: B

variables:
  counter: 0