


stages:
  - stage: 'A'
    jobs:
      - job: 'A'
        steps:
          - powershell: |
              Write-Host "##vso[task.setvariable variable=A;isOutput=true]'A'"
            name: 'A'

  - stage: 'B'
    jobs:
      - job: 'B'
        condition: $[ eq(stageDependencies.Download_Variables.Download_Variables.outputs['Set_Variables.DeploymentBuildSuffix'], 'A') ]
        steps:
          - powershell: |
            name: 'B'