stages:
- stage: Variables
  dependsOn: []
  jobs:
    - job: Prepare
      steps:
        - powershell: |
            $variables = @{
              dotnetQueue = 0
            }
            Write-Host $variables
            New-Item -Path "$(System.DefaultWorkingDirectory)" -Name "Variables" -ItemType "directory" -Force
            $variables | ConvertTo-Json | Out-File "$(System.DefaultWorkingDirectory)/Variables/variables.json"
          displayName: Pre Deploy
        - task: PublishPipelineArtifact@1
          displayName: 'Publish Variables as artifact'
          inputs:
            targetPath: $(System.DefaultWorkingDirectory)/variables
            artifactName: Variables

- stage: A
  dependsOn: [Variables]
  jobs:
    - job: A
      steps:
        - task: AzureCLI@2
          inputs:
            azureSubscription: 'j-arguello'
            scriptType: pscore
            scriptLocation: inlineScript
            inlineScript: |
              Start-Sleep -s 5
              Write-Host "##vso[task.setvariable variable=queue;isOutput=true]1"

        - powershell: |
            Write-Host "Deploy"
          displayName: Deploy

- stage: B
  dependsOn: [Variables]
  jobs:
    - job: 
      steps:
        - powershell: |
            while($true) { 
              az pipelines runs artifact download --run-id $(Build.BuildId) --detect true --artifact-name "Variables" --path "./powershell"

              $json = Get-Content "./powershell/variables.json" | ConvertFrom-Json

              if($json.dotnetQueue -lt 1) {
                "Checking"
                Start-Sleep -s 1
                write-host "$(queue)"
              } else {
                $json.dotnetQueue = $json.dotnetQueue + 1
                az pipelines runs artifact upload --run-id $(Build.BuildId) --detect true --artifact-name "Variables" --path "./powershell"
                Break
              }
            }
            Write-Host "test"
          displayName: Pre Deploy
        - powershell: |
            Write-Host "Deploy"
          displayName: Deploy

variables:
  counter: 0