stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - pwsh: |
        $greeting = "Hello World"
        Write-Host "##vso[task.setvariable variable=StepVariable;isOutput=true]${greeting}"
      name: BuildStep
 
- stage: Test
  dependsOn: Build
  jobs:
    - template: test
      parameters:
        name: $[stageDependencies.Build.BuildJob.outputs['BuildStep.StepVariable']]