stages:
- stage: bffnsimplehostbotdotnet
  dependsOn: []
  jobs: 
    - job:
      steps: 
        - powershell: echo "test"

- stage: bffnsimplehostbotdotnet21
  dependsOn: []
  jobs: 
    - job:
      steps: 
        - powershell: echo "test"

- stage: bffnechoskillbotdotnet
  dependsOn: []
  jobs: 
    - job:
      steps: 
        - powershell: echo "test"

- stage: bffnechoskillbotdotnet21
  dependsOn: []
  jobs: 
    - job:
      steps: 
        - powershell: echo "test"

- stage: bffnechoskillbotdotnetv3
  dependsOn: []
  jobs: 
    - job:
      steps: 
        - powershell: echo "test"

- stage: bffnwaterfallhostbotdotnet
  dependsOn: []
  jobs: 
    - job:
      steps: 
        - powershell: echo "test"

- stage: Deploy
  dependsOn: [
    bffnsimplehostbotdotnet,
    bffnsimplehostbotdotnet21,
    bffnechoskillbotdotnet,
    bffnechoskillbotdotnet21,
    bffnechoskillbotdotnetv3,
    bffnwaterfallhostbotdotnet
  ]
  jobs:
    - job: Test
      strategy:
        maxParallel: 3
        matrix:
          bffnsimplehostbotdotnet: {}
          bffnsimplehostbotdotnet21: {}
          bffnechoskillbotdotnet: {}
          bffnechoskillbotdotnet21: {}
          bffnechoskillbotdotnetv3: {}
          bffnwaterfallhostbotdotnet: {}
      steps: 
        - powershell: echo "test"