stages:
- stage: A
  dependsOn: []
  jobs:
    - job: 
      steps:
        - powershell: |
            Start-Sleep -s 5
            Write-Host "##vso[task.setvariable variable=queue;isOutput=true]1"
          displayName: Pre Deploy
        - powershell: |
            Write-Host "Deploy"
          displayName: Deploy

- stage: B
  dependsOn: []
  jobs:
    - job: 
      steps:
        - powershell: |
            do { 
              "Checking"
              Start-Sleep -s 1
            } while ($(queue) -eq 0)
            Write-Host "test"
          displayName: Pre Deploy
        - powershell: |
            Write-Host "Deploy"
          displayName: Deploy

variables:
  counter: 0